/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author simpl
 */
public class CalculatorUI extends javax.swing.JFrame {

    /**
     * Creates new form CalculatorUI
     */
    public CalculatorUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton9 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jtxtResult = new javax.swing.JTextField();
        jButtonInt3 = new javax.swing.JButton();
        jButtonInt1 = new javax.swing.JButton();
        jButtonInt2 = new javax.swing.JButton();
        jButtonInt6 = new javax.swing.JButton();
        jButtonInt4 = new javax.swing.JButton();
        jButtonInt5 = new javax.swing.JButton();
        jButtonInt9 = new javax.swing.JButton();
        jButtonInt7 = new javax.swing.JButton();
        jButtonInt8 = new javax.swing.JButton();
        jButtonESC = new javax.swing.JButton();
        jButtonInt0 = new javax.swing.JButton();
        jButtonEquals = new javax.swing.JButton();
        jButtonMultiplication = new javax.swing.JButton();
        jButtonDivision = new javax.swing.JButton();
        jButtonAddition = new javax.swing.JButton();
        jButtonSubtraction = new javax.swing.JButton();

        jButton9.setText("jButton1");

        jButton14.setText("jButton1");

        jButton8.setText("jButton1");

        jButton6.setText("jButton1");

        jButton3.setText("jButton1");

        jButton7.setText("jButton1");

        jButton10.setText("jButton1");

        jButton5.setText("jButton1");

        jButton11.setText("jButton1");

        jButton13.setText("jButton1");

        jButton12.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtxtResult.setFont(new java.awt.Font("Myanmar Text", 1, 24)); // NOI18N
        jtxtResult.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtResultActionPerformed(evt);
            }
        });

        jButtonInt3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonInt3.setText("3");
        jButtonInt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInt3ActionPerformed(evt);
            }
        });

        jButtonInt1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonInt1.setText("1");
        jButtonInt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInt1ActionPerformed(evt);
            }
        });

        jButtonInt2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonInt2.setText("2");
        jButtonInt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInt2ActionPerformed(evt);
            }
        });

        jButtonInt6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonInt6.setText("6");
        jButtonInt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInt6ActionPerformed(evt);
            }
        });

        jButtonInt4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonInt4.setText("4");
        jButtonInt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInt4ActionPerformed(evt);
            }
        });

        jButtonInt5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonInt5.setText("5");
        jButtonInt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInt5ActionPerformed(evt);
            }
        });

        jButtonInt9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonInt9.setText("9");
        jButtonInt9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInt9ActionPerformed(evt);
            }
        });

        jButtonInt7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonInt7.setText("7");
        jButtonInt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInt7ActionPerformed(evt);
            }
        });

        jButtonInt8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonInt8.setText("8");
        jButtonInt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInt8ActionPerformed(evt);
            }
        });

        jButtonESC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonESC.setText("ESC");
        jButtonESC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonESCActionPerformed(evt);
            }
        });

        jButtonInt0.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonInt0.setText("0");
        jButtonInt0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInt0ActionPerformed(evt);
            }
        });

        jButtonEquals.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonEquals.setText("=");
        jButtonEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEqualsActionPerformed(evt);
            }
        });

        jButtonMultiplication.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonMultiplication.setText("x");
        jButtonMultiplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultiplicationActionPerformed(evt);
            }
        });

        jButtonDivision.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonDivision.setText("÷");
        jButtonDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDivisionActionPerformed(evt);
            }
        });

        jButtonAddition.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonAddition.setText("+");
        jButtonAddition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdditionActionPerformed(evt);
            }
        });

        jButtonSubtraction.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonSubtraction.setText("-");
        jButtonSubtraction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubtractionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtResult, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonInt0, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonInt7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonInt1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonInt4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonInt5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonInt6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonInt8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonInt9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jButtonEquals, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonESC, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jButtonSubtraction, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButtonMultiplication, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonInt2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonInt3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonAddition, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtxtResult, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonInt1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonInt2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonInt3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAddition, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonInt4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonInt5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonInt6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSubtraction, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonInt7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonInt8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonInt9, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMultiplication, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonInt0, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEquals, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonESC, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void InputNums(String i){
        String Nums = jtxtResult.getText() + i;
        jtxtResult.setText(Nums);
    }
    private void jButtonInt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInt1ActionPerformed
        // TODO add your handling code here:
        InputNums("1");
    }//GEN-LAST:event_jButtonInt1ActionPerformed

    private void jButtonInt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInt3ActionPerformed
        // TODO add your handling code here:
        InputNums("3");
    }//GEN-LAST:event_jButtonInt3ActionPerformed

    private void jButtonInt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInt2ActionPerformed
        // TODO add your handling code here:
        InputNums("2");
    }//GEN-LAST:event_jButtonInt2ActionPerformed

    private void jButtonInt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInt6ActionPerformed
        // TODO add your handling code here:
        InputNums("6");
    }//GEN-LAST:event_jButtonInt6ActionPerformed

    private void jButtonInt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInt4ActionPerformed
        // TODO add your handling code here:
        InputNums("4");
    }//GEN-LAST:event_jButtonInt4ActionPerformed

    private void jButtonInt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInt5ActionPerformed
        // TODO add your handling code here:
        InputNums("5");
    }//GEN-LAST:event_jButtonInt5ActionPerformed

    private void jButtonInt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInt9ActionPerformed
        // TODO add your handling code here:
        InputNums("9");
    }//GEN-LAST:event_jButtonInt9ActionPerformed

    private void jButtonInt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInt7ActionPerformed
        // TODO add your handling code here:
        InputNums("7");
    }//GEN-LAST:event_jButtonInt7ActionPerformed

    private void jButtonInt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInt8ActionPerformed
        // TODO add your handling code here:
        InputNums("8");
    }//GEN-LAST:event_jButtonInt8ActionPerformed

    private void jButtonESCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonESCActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButtonESCActionPerformed

    private void jButtonInt0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInt0ActionPerformed
        // TODO add your handling code here:
        InputNums("0");
    }//GEN-LAST:event_jButtonInt0ActionPerformed

    private void jButtonEqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEqualsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEqualsActionPerformed

    private void jButtonMultiplicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultiplicationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMultiplicationActionPerformed

    private void jButtonDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDivisionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDivisionActionPerformed

    private void jButtonAdditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdditionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAdditionActionPerformed

    private void jButtonSubtractionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubtractionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSubtractionActionPerformed

    private void jtxtResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtResultActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonAddition;
    private javax.swing.JButton jButtonDivision;
    private javax.swing.JButton jButtonESC;
    private javax.swing.JButton jButtonEquals;
    private javax.swing.JButton jButtonInt0;
    private javax.swing.JButton jButtonInt1;
    private javax.swing.JButton jButtonInt2;
    private javax.swing.JButton jButtonInt3;
    private javax.swing.JButton jButtonInt4;
    private javax.swing.JButton jButtonInt5;
    private javax.swing.JButton jButtonInt6;
    private javax.swing.JButton jButtonInt7;
    private javax.swing.JButton jButtonInt8;
    private javax.swing.JButton jButtonInt9;
    private javax.swing.JButton jButtonMultiplication;
    private javax.swing.JButton jButtonSubtraction;
    private javax.swing.JTextField jtxtResult;
    // End of variables declaration//GEN-END:variables
}
